# Generated by Django 2.1.2 on 2021-04-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iprocone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Member',
        ),
    ]
